# Site settings
title: Showdog
tagline: Single page Jekyll template for people with something to show off
email: kaldejm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jmkaldenbach
github_url:  https://github.com/jkaldenbach/showdog
linkedin_url: https://www.linkedin.com/pub/justin-kaldenbach/27/b87/9b3

# Build settings
markdown: kramdown

collections:
- sections
